name: Release

on:
  push:
    tags:
      - '*'


jobs:
  release-plugin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1

      - name: Build
        run: cargo build --release --target wasm32-wasip1

      - name: Create SHA256 checksum
        id: sha256
        run: |
          echo "sha=$(sha256sum target/wasm32-wasip1/release/plugin.wasm | cut -d ' ' -f 1)" >> "$GITHUB_OUTPUT"

      - name: Create SHA256 checksum file
        run: echo ${{ steps.sha256.outputs.sha }} > target/wasm32-wasip1/release/plugin.wasm.sha256

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/wasm32-wasip1/release/plugin.wasm
            target/wasm32-wasip1/release/plugin.wasm.sha256
          name: v${{ github.ref_name }}
          body: |
            SHA256 checksums: ${{ steps.sha256.outputs.sha }}
          append_body: true
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
